[package]
name = "qft"
version = "0.5.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iui.git = "https://github.com/rust-native-ui/libui-rs"
rand = "0"
time = "0"
